# Generated by Django 5.1.4 on 2025-01-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_email_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse_manager', 'Warehouse Manager')], max_length=50),
        ),
    ]
