# Generated by Django 5.1.7 on 2025-03-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_warehouse_handles_expiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
