# Generated by Django 5.1.4 on 2025-02-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse_manager', 'Warehouse Manager'), ('custumer', 'custumer')], max_length=50),
        ),
    ]
