# Generated by Django 5.1.4 on 2025-02-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse_manager', 'Warehouse Manager'), ('customer', 'customer')], max_length=50),
        ),
    ]
