# Generated by Django 5.1.7 on 2025-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_stock",
            field=models.IntegerField(default=10),
        ),
    ]
