# Generated by Django 5.1.7 on 2025-03-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0002_product_min_stock"),
        ("user", "0005_warehouse_handles_expiring"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.warehouse",
            ),
        ),
    ]
