# Generated by Django 5.1.4 on 2025-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
