# Generated by Django 5.1.7 on 2025-03-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_customuser_created_by_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="handles_expiring",
            field=models.BooleanField(default=False),
        ),
    ]
