# Generated by Django 5.2.1 on 2025-07-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
